# Site
name: "Jazz Peh"
title: "A 80% debugging, 20% coding programmer life"
description: null
logo: null
favicon: 'assets/images/favicon.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: null
include: ["_pages"]
permalink: /:title/
email: wowthemesnet@gmail.com
github: 'https://github.com/jazzpeh'
linkedin: 'https://www.linkedin.com/in/jazz-peh/'

# Authors
authors:
  jazz:
    name: Jazz
    display_name: Jazz
    gravatar: 4a1229bd40b1fcd153f70d056e6fed9a
    email: jazzpehz@gmail.com
    web: https://www.linkedin.com/in/jazz-peh
    twitter: https://twitter.com/jazzpeh
    description: "A forever learning programmer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Github Pages
lsi: false
safe: true
source: ''
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
